### ISSUE TITLE
ESLint error and readme suggestion

### ISSUE THREAD

**Issue by trust2065** [smallpaes/google-map-api-practice-map#1]
1. While initialing the project ESlint is complaining about `'google' is not defined`  and a minor non-used variable is also detect by ESlint.

2. Add a step with the accurate URL such as (http://localhost:8080/#/restaurants). Otherwise setup http://localhost:8080/#/restaurants as initial page after running `npm run serve`

**Comment by smallpaes** [comment]
Hi @trust2065 ,
Thank you for pointing out these issues. The latest update should have solved the ESlint error while initializing and included the step with the correct URL to the initial page on README. Kindly let me know should there be any other issue, thank you very much.
